services:
  mysql:
    image: 'mysql:8.0'   
    environment:
      MYSQL_DATABASE: calor-noche
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - '3306:3306'
